## Controlliamo se funziona jupyter (funzione di Pandas)

### Provo a stampare "Ciao mondo!"

In [12]:
print("Ciao mondo!")

Ciao mondo!

## Primo passo con pandas

### Crea un DataFrame = Dictionary = Dataset

In [33]:
import pandas as pd

# Abbiamo creato un dataframe(dati) = dataset
data = {
    "Nome": ["Filippo", "Salomon", "Asia", "Ana", "Cristian", "Miriam"], 
    "Cognome": ["Battaglia", "Rossi", "Verdi", "Neri", "Gialli", "Blu"],
    "Voto": [8, 10, 9, 7, 11, 9]
    }

df = pd.DataFrame(data) # Lo trasformiamo in un dataframe

#### df visualizziamo il dataframe formato come tabella Excel

In [34]:
df

       Nome    Cognome  Voto
0   Filippo  Battaglia     8
1   Salomon      Rossi    10
2      Asia      Verdi     9
3       Ana       Neri     7
4  Cristian     Gialli    11
5    Miriam        Blu     9

#### print(df) si visualizza il dataframe come testo, simile ad un file CSV

In [ ]:
print(df)

#### df.head(1) # visualizza solo la prima riga del dataframe

In [ ]:
df.head(1) # visualizza solo la prima riga del dataframe

#### df.tail(2) # visualizza le ultime 2 righe del dataframe

In [ ]:
df.tail(2) # visualizza solo le ultime 2 righe del dataframe

#### df.info() # ci da informazioni sul dataframe, come il numero di righe, colonne, tipi di dati, ecc.

In [ ]:
df.info() # visualizza informazioni sul dataframe, come il numero di righe, colonne e tipi di dati

#### df.describe() # ci da informazioni statistiche sul dataframe, come la media, la deviazione standard, i valori minimi e massimi, ecc. (solo per colonne numeriche)

In [ ]:
df.describe() # visualizza statistiche descrittive del dataframe, come la media, la deviazione standard e i quartili per le colonne numeriche


#### df[["Nome","Cognome", "Età"]] # visualizza solo le colonne "Nome", "Cognome" e "Età" del dataframe
#### df["Età"] # visualizza solo la colonna "Età" del dataframe

In [58]:
df["Nome"] # visualizza solo la colonna "Nome" del dataframe

3         Ana
0     Filippo
2        Asia
5      Miriam
1     Salomon
4    Cristian
Name: Nome, dtype: str

Filtrare i dati per età

In [59]:
df[df["Voto"] > 8] # visualizza solo le righe del dataframe in cui il voto è maggiore di 8

       Nome Cognome  Voto  Promosso
2      Asia   Verdi     9      True
5    Miriam     Blu     9      True
1   Salomon   Rossi    10      True
4  Cristian  Gialli    11      True

Calcolare media

In [60]:
df["Voto"].mean() # calcola la media della colonna "Voto"

np.float64(9.0)

Aggiornare una colonna

In [61]:
df["Promosso"] = df["Voto"] > 8 # crea una nuova colonna "Promosso" che indica se il voto è maggiore di 8
df

       Nome    Cognome  Voto  Promosso
3       Ana       Neri     7     False
0   Filippo  Battaglia     8     False
2      Asia      Verdi     9      True
5    Miriam        Blu     9      True
1   Salomon      Rossi    10      True
4  Cristian     Gialli    11      True

Mettere in ordine decrescente

In [62]:
df.sort_values(by="Voto", ascending=False, inplace=True) # ordina il dataframe in base alla colonna "Voto" in ordine decrescente
df

       Nome    Cognome  Voto  Promosso
4  Cristian     Gialli    11      True
1   Salomon      Rossi    10      True
5    Miriam        Blu     9      True
2      Asia      Verdi     9      True
0   Filippo  Battaglia     8     False
3       Ana       Neri     7     False

Mettere in ordine crescente

In [63]:
df.sort_values(by="Voto", ascending=True, inplace=True) # ordina il dataframe in base alla colonna "Voto" in ordine crescente
df

       Nome    Cognome  Voto  Promosso
3       Ana       Neri     7     False
0   Filippo  Battaglia     8     False
2      Asia      Verdi     9      True
5    Miriam        Blu     9      True
1   Salomon      Rossi    10      True
4  Cristian     Gialli    11      True

ESERCIZIO 1:
    Creare un DataFrame "corso" con 4 colonne(nomeCorso, descrizione, dataInizio, dataFIne) e stampare il contenuto

In [64]:
# Esercizio 1

corso = {
    "nomeCorso": ["Python", "Java", "CSS", "JavaScript", "HTML", "Pandas"],
    "descrizione": ["Corso di Python", "Corso di Java", "Corso di CSS", "Corso di JavaScript", "Corso di HTML", "Corso di Pandas"],
    "dataInizio": ["2024-01-15", "2024-02-01", "2024-03-10", "2024-04-20", "2024-05-05", "2024-06-10"],
    "dataFine": ["2024-02-15", "2024-03-01", "2024-04-10", "2024-05-20", "2024-06-05", "2024-07-10"]
}

corso = pd.DataFrame(corso)

corso

    nomeCorso          descrizione  dataInizio    dataFine
0      Python      Corso di Python  2024-01-15  2024-02-15
1        Java        Corso di Java  2024-02-01  2024-03-01
2         CSS         Corso di CSS  2024-03-10  2024-04-10
3  JavaScript  Corso di JavaScript  2024-04-20  2024-05-20
4        HTML        Corso di HTML  2024-05-05  2024-06-05
5      Pandas      Corso di Pandas  2024-06-10  2024-07-10


ESERCIZIO 2:
    Creare un DataFrame studenti con 4 colonne(nome, cognome, dataNascita, email, telefono) e stampa il contenuto

In [65]:
# Esercizio 2

studenti = {
    "nome": ["Cristian", "Giovanni", "Maria", "Mia", "Flavia", "Luca", "Romeo"],
    "cognome": ["Romolo", "Rossi", "Ricciardi", "Lopez", "Neri", "Bianchi", "Giulietta"],
    "dataNascita": ["1990-05-15", "1992-08-20", "1988-12-10", "1995-03-25", "1991-11-30", "1989-07-12", "1993-09-18"],
    "email": ["cristian.romolo@email.com", "giovanni.rossi@email.com", "maria.ricciardi@email.com", "mia.lopez@email.com", "flavia.neri@email.com", "luca.bianchi@email.com", "romeo.giulietta@email.com"],
    "telefono": ["1234567890", "0987654321", "5555555555", "4444444444", "3333333333", "6666666666", "7777777777"]
}

studenti = pd.DataFrame(studenti)

studenti

       nome    cognome dataNascita                      email    telefono
0  Cristian     Romolo  1990-05-15  cristian.romolo@email.com  1234567890
1  Giovanni      Rossi  1992-08-20   giovanni.rossi@email.com  0987654321
2     Maria  Ricciardi  1988-12-10  maria.ricciardi@email.com  5555555555
3       Mia      Lopez  1995-03-25        mia.lopez@email.com  4444444444
4    Flavia       Neri  1991-11-30      flavia.neri@email.com  3333333333
5      Luca    Bianchi  1989-07-12     luca.bianchi@email.com  6666666666
6     Romeo  Giulietta  1993-09-18  romeo.giulietta@email.com  7777777777